configuring /vagrant/cases/fiasco_17_10/Configs/0.config
make -C build oldconfig
make[1]: Entering directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:8: /home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile: No such file or directory
make[1]: *** No rule to make target '/home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile'.  Stop.
make[1]: Leaving directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:95: recipe for target 'oldconfig' failed
make: *** [oldconfig] Error 2

real	0m0.024s
user	0m0.000s
sys	0m0.008s
Traceback (most recent call last):
  File "/vagrant/scripts/compare_configs.py", line 112, in <module>
    if config_vals1[name] != config_vals2[name]:
KeyError: 'CONFIG_PF_EXYNOS_PKG_IDS'
diff result: 1
configuring /vagrant/cases/fiasco_17_10/Configs/1.config
make -C build oldconfig
make[1]: Entering directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:8: /home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile: No such file or directory
make[1]: *** No rule to make target '/home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile'.  Stop.
make[1]: Leaving directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:95: recipe for target 'oldconfig' failed
make: *** [oldconfig] Error 2

real	0m0.007s
user	0m0.000s
sys	0m0.000s
Traceback (most recent call last):
  File "/vagrant/scripts/compare_configs.py", line 112, in <module>
    if config_vals1[name] != config_vals2[name]:
KeyError: 'CONFIG_PF_EXYNOS_PKG_IDS'
diff result: 1
configuring /vagrant/cases/fiasco_17_10/Configs/2.config
make -C build oldconfig
make[1]: Entering directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:8: /home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile: No such file or directory
make[1]: *** No rule to make target '/home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile'.  Stop.
make[1]: Leaving directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:95: recipe for target 'oldconfig' failed
make: *** [oldconfig] Error 2

real	0m0.008s
user	0m0.000s
sys	0m0.000s
Traceback (most recent call last):
  File "/vagrant/scripts/compare_configs.py", line 112, in <module>
    if config_vals1[name] != config_vals2[name]:
KeyError: 'CONFIG_PF_EXYNOS_PKG_IDS'
diff result: 1
configuring /vagrant/cases/fiasco_17_10/Configs/3.config
make -C build oldconfig
make[1]: Entering directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:8: /home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile: No such file or directory
make[1]: *** No rule to make target '/home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile'.  Stop.
make[1]: Leaving directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:95: recipe for target 'oldconfig' failed
make: *** [oldconfig] Error 2

real	0m0.008s
user	0m0.000s
sys	0m0.000s
Traceback (most recent call last):
  File "/vagrant/scripts/compare_configs.py", line 112, in <module>
    if config_vals1[name] != config_vals2[name]:
KeyError: 'CONFIG_PF_EXYNOS_PKG_IDS'
diff result: 1
configuring /vagrant/cases/fiasco_17_10/Configs/4.config
make -C build oldconfig
make[1]: Entering directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:8: /home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile: No such file or directory
make[1]: *** No rule to make target '/home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile'.  Stop.
make[1]: Leaving directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:95: recipe for target 'oldconfig' failed
make: *** [oldconfig] Error 2

real	0m0.008s
user	0m0.000s
sys	0m0.000s
Traceback (most recent call last):
  File "/vagrant/scripts/compare_configs.py", line 112, in <module>
    if config_vals1[name] != config_vals2[name]:
KeyError: 'CONFIG_PF_EXYNOS_PKG_IDS'
diff result: 1
configuring /vagrant/cases/fiasco_17_10/Configs/5.config
make -C build oldconfig
make[1]: Entering directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:8: /home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile: No such file or directory
make[1]: *** No rule to make target '/home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile'.  Stop.
make[1]: Leaving directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:95: recipe for target 'oldconfig' failed
make: *** [oldconfig] Error 2

real	0m0.007s
user	0m0.000s
sys	0m0.000s
Traceback (most recent call last):
  File "/vagrant/scripts/compare_configs.py", line 112, in <module>
    if config_vals1[name] != config_vals2[name]:
KeyError: 'CONFIG_PF_EXYNOS_PKG_IDS'
diff result: 1
configuring /vagrant/cases/fiasco_17_10/Configs/6.config
make -C build oldconfig
make[1]: Entering directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:8: /home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile: No such file or directory
make[1]: *** No rule to make target '/home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile'.  Stop.
make[1]: Leaving directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:95: recipe for target 'oldconfig' failed
make: *** [oldconfig] Error 2

real	0m0.007s
user	0m0.000s
sys	0m0.000s
Traceback (most recent call last):
  File "/vagrant/scripts/compare_configs.py", line 112, in <module>
    if config_vals1[name] != config_vals2[name]:
KeyError: 'CONFIG_PF_EXYNOS_UART_NR'
diff result: 1
configuring /vagrant/cases/fiasco_17_10/Configs/7.config
make -C build oldconfig
make[1]: Entering directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:8: /home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile: No such file or directory
make[1]: *** No rule to make target '/home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile'.  Stop.
make[1]: Leaving directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:95: recipe for target 'oldconfig' failed
make: *** [oldconfig] Error 2

real	0m0.008s
user	0m0.000s
sys	0m0.000s
Traceback (most recent call last):
  File "/vagrant/scripts/compare_configs.py", line 112, in <module>
    if config_vals1[name] != config_vals2[name]:
KeyError: 'CONFIG_PF_EXYNOS_PKG_IDS'
diff result: 1
configuring /vagrant/cases/fiasco_17_10/Configs/8.config
make -C build oldconfig
make[1]: Entering directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:8: /home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile: No such file or directory
make[1]: *** No rule to make target '/home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile'.  Stop.
make[1]: Leaving directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:95: recipe for target 'oldconfig' failed
make: *** [oldconfig] Error 2

real	0m0.007s
user	0m0.000s
sys	0m0.000s
Traceback (most recent call last):
  File "/vagrant/scripts/compare_configs.py", line 112, in <module>
    if config_vals1[name] != config_vals2[name]:
KeyError: 'CONFIG_PF_EXYNOS_PKG_IDS'
diff result: 1
configuring /vagrant/cases/fiasco_17_10/Configs/9.config
make -C build oldconfig
make[1]: Entering directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:8: /home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile: No such file or directory
make[1]: *** No rule to make target '/home/vagrant/fiasco-17.10/src/kernel/fiasco/src/Makefile'.  Stop.
make[1]: Leaving directory '/home/vagrant/fiasco_17_10/src/kernel/fiasco/build'
Makefile:95: recipe for target 'oldconfig' failed
make: *** [oldconfig] Error 2

real	0m0.008s
user	0m0.000s
sys	0m0.000s
Traceback (most recent call last):
  File "/vagrant/scripts/compare_configs.py", line 112, in <module>
    if config_vals1[name] != config_vals2[name]:
KeyError: 'CONFIG_PF_EXYNOS_PKG_IDS'
diff result: 1
has 0 duplicate config files
